name: MacM1

on:
  push:
#    paths:
#      - '**.py'
#      - '**.yml'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    name: Python ${{ matrix.python-version }}
#    runs-on: macos-13-arm64
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]

    steps:
      - name: install chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: install firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: install edge
        run: brew install --cask microsoft-edge

      - name: Verify Edge Installation
        run: /Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge --version

      - name: remove native drivers
        run: |
          rm /usr/local/share/chromedriver-mac-arm64/chromedriver

################################################################################
# SETUP TEST 
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
