name: Linux

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        python-version: [
#          "3.10",
          "3.11"
        ]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#          cache: 'pip'



# INSTALL BROWSERS
      - name: Install browsers on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common apt-transport-https wget curl
          
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          
          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get update && sudo apt install microsoft-edge-beta
          
          wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
          sudo add-apt-repository "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free"
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install opera-stable
          
          sudo apt-get install chromium-browser
          
#          sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
#          echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
#          sudo apt update
#          sudo apt install brave-browser

      - name: install chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: install firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
      
      - name: setup edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable
      
################################################################################
# SETUP TEST 
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"

      - name: Configure Poetry
        shell: bash
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        shell: bash
        run: |
          poetry install --with dev

      - name: Test with pytest
        run: |
          pytest -vv
