name: Windows

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
#  schedule:
#    - cron:  '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    name: Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        python-version: [
#          "3.10",
          "3.11"
        ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Install browsers on Windows
        if: runner.os == 'Windows'
        shell: powershell
#          choco install chromium opera brave googlechrome --no-progress -y --force
#          choco install chromium googlechrome firefox --no-progress -y --force
        run: |
          choco install googlechrome --no-progress -y --force
      
      - name: Test with tox
        run: tox
